<?xml version="1.0" encoding="UTF-8"?><testrun name="M1PublicTests" project="harrypotter" tests="123" started="123" failures="4" errors="15" ignored="0">
  <testsuite name="harrypotter.tests.M1PublicTests" time="22.435">
    <testcase name="testConstructorTask" classname="harrypotter.tests.M1PublicTests" time="0.01"/>
    <testcase name="testConstructorChampionCellInitialization" classname="harrypotter.tests.M1PublicTests" time="0.004"/>
    <testcase name="testInstanceVariableWizardSpellsSetter" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testInstanceVariableTaskChampionsSetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testConstructorRavenclawWizard" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testFirstTaskMapObstacleHPRange" classname="harrypotter.tests.M1PublicTests" time="0.162"/>
    <testcase name="testInstanceVariableSpellDefaultCooldownGetter" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testInstanceVariableSpellCoolDownSetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableTaskChampions" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableCollectibleSetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableChampionCellGetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableTaskAllowedMoves" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testMethodInInterfaceChampion" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testClassIsSubClassSlytherinWizard" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testClassIsSubClassThirdTask" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testConstructorSecondTaskInitialization" classname="harrypotter.tests.M1PublicTests" time="0.115">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 100 milliseconds
	at harrypotter.model.tournament.Task.task2(Task.java:171)
	at harrypotter.model.tournament.SecondTask.generateMap(SecondTask.java:21)
	at harrypotter.model.tournament.Task.&lt;init&gt;(Task.java:57)
	at harrypotter.model.tournament.SecondTask.&lt;init&gt;(SecondTask.java:11)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at harrypotter.tests.M1PublicTests.testConstructorSecondTaskInitialization(M1PublicTests.java:341)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testInstanceVariableSpellDefaultCooldownSetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testLoadedPotions" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableRelocatingSpellRangeGetter" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testMethodInInterfaceMethodUseTrait" classname="harrypotter.tests.M1PublicTests" time="0.009"/>
    <testcase name="testConstructorRelocatingSpellInitialization" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableChampionCellSetter" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testInstanceVariableRelocatingSpellRange" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariablesRelocatingSpellInherited" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testFirstConstructorGryffindorWizardInitialization" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableRelocatingSpellRangeSetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testConstructorSpell" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testClassIsAbstractCell" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testClassIsAbstractTask" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testMethodreadMapInThirdTask" classname="harrypotter.tests.M1PublicTests" time="0.102">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 100 milliseconds
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M1PublicTests.testMethodExistsInClass(M1PublicTests.java:2051)
	at harrypotter.tests.M1PublicTests.testMethodreadMapInThirdTask(M1PublicTests.java:1402)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testClassIsAbstractObstacle" classname="harrypotter.tests.M1PublicTests" time="0.005"/>
    <testcase name="testMethodInSlytherinWizardTrait" classname="harrypotter.tests.M1PublicTests" time="0.005">
      <failure>java.lang.AssertionError: The useTrait method in class harrypotter.model.character.SlytherinWizard should be implemented.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M1PublicTests.testMethodExistsInClass(M1PublicTests.java:2014)
	at harrypotter.tests.M1PublicTests.testMethodInSlytherinWizardTrait(M1PublicTests.java:1381)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testInstanceVariableTaskCurrentChampGetter" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testInstanceVariableObstacleGetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableTournamentChampions" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testFirstTaskMapChampionCount" classname="harrypotter.tests.M1PublicTests" time="0.011"/>
    <testcase name="testInstanceVariableTournamentChampionsGetter" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testSecondTaskMerpersonDmgHpRange" classname="harrypotter.tests.M1PublicTests" time="5.003">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 5000 milliseconds
	at harrypotter.model.tournament.Task.task2(Task.java:171)
	at harrypotter.model.tournament.SecondTask.generateMap(SecondTask.java:21)
	at harrypotter.model.tournament.Task.&lt;init&gt;(Task.java:57)
	at harrypotter.model.tournament.SecondTask.&lt;init&gt;(SecondTask.java:11)
	at harrypotter.tests.M1PublicTests.testSecondTaskMerpersonDmgHpRange(M1PublicTests.java:1699)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testFirstConstructorHufflepuffWizardInitialization" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testInstanceVariableSpellCost" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testInstanceVariableSpellName" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testSecondTaskMapTreasureCount" classname="harrypotter.tests.M1PublicTests" time="2.003">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 2000 milliseconds
	at harrypotter.model.tournament.Task.task2(Task.java:171)
	at harrypotter.model.tournament.SecondTask.generateMap(SecondTask.java:21)
	at harrypotter.model.tournament.Task.&lt;init&gt;(Task.java:57)
	at harrypotter.model.tournament.SecondTask.&lt;init&gt;(SecondTask.java:11)
	at harrypotter.tests.M1PublicTests.testSecondTaskMapTreasureCount(M1PublicTests.java:1665)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testClassIsAbstractSpell" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableObstacleCell" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testConstructorRelocatingSpell" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableWizardHp" classname="harrypotter.tests.M1PublicTests" time="0.004"/>
    <testcase name="testInstanceVariableWizardIp" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableTaskCurrentChampSetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableObstacleSetter" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testInstanceVariableTournamentChampionsSetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testClassImplementsInterfaceHufflepuffWizard" classname="harrypotter.tests.M1PublicTests" time="0.101">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 100 milliseconds
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M1PublicTests.testClassImplementsInterface(M1PublicTests.java:2119)
	at harrypotter.tests.M1PublicTests.testClassImplementsInterfaceHufflepuffWizard(M1PublicTests.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testInstanceVariableWizardName" classname="harrypotter.tests.M1PublicTests" time="0.005"/>
    <testcase name="testClassIsAbstractCollectible" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testConstructorFirstTaskInitialization" classname="harrypotter.tests.M1PublicTests" time="0.004"/>
    <testcase name="testInstanceVariableTaskTraitActivatedGetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableTaskCurrentChamp" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testSecondTaskMapObstacleCount" classname="harrypotter.tests.M1PublicTests" time="2.002">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 2000 milliseconds
	at harrypotter.model.tournament.Task.task2(Task.java:171)
	at harrypotter.model.tournament.SecondTask.generateMap(SecondTask.java:21)
	at harrypotter.model.tournament.Task.&lt;init&gt;(Task.java:57)
	at harrypotter.model.tournament.SecondTask.&lt;init&gt;(SecondTask.java:11)
	at harrypotter.tests.M1PublicTests.testSecondTaskMapObstacleCount(M1PublicTests.java:1496)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testClassIsSubClassMerpersonObstacle" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testInstanceVariableWizardInventoryGetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testClassIsSubClassRavenclawWizard" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testConstructorPhysicalObstacleInitialization" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testConstructorObstacleCell" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testInstanceVariableTaskMap" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableTaskTraitActivated" classname="harrypotter.tests.M1PublicTests" time="0.005"/>
    <testcase name="testClassIsAbstractWizard" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableTaskTraitActivatedSetter" classname="harrypotter.tests.M1PublicTests" time="0.101">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 100 milliseconds
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M1PublicTests.testSetterMethodExistsInClass(M1PublicTests.java:1981)
	at harrypotter.tests.M1PublicTests.testInstanceVariableTaskTraitActivatedSetter(M1PublicTests.java:1099)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testMethodLoadSpellsInTournament" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableTournamentSpellsGetter" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testSecondTaskMapPotionRandomlyChosen" classname="harrypotter.tests.M1PublicTests" time="5.003">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 5000 milliseconds
	at harrypotter.model.tournament.Task.task2(Task.java:171)
	at harrypotter.model.tournament.SecondTask.generateMap(SecondTask.java:21)
	at harrypotter.model.tournament.Task.&lt;init&gt;(Task.java:57)
	at harrypotter.model.tournament.SecondTask.&lt;init&gt;(SecondTask.java:11)
	at harrypotter.tests.M1PublicTests.testSecondTaskMapPotionRandomlyChosen(M1PublicTests.java:1535)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testSecondTaskMapTreasureCorrectlyAssigned" classname="harrypotter.tests.M1PublicTests" time="2.003">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 2000 milliseconds
	at harrypotter.model.tournament.Task.task2(Task.java:171)
	at harrypotter.model.tournament.SecondTask.generateMap(SecondTask.java:21)
	at harrypotter.model.tournament.Task.&lt;init&gt;(Task.java:57)
	at harrypotter.model.tournament.SecondTask.&lt;init&gt;(SecondTask.java:11)
	at harrypotter.tests.M1PublicTests.testSecondTaskMapTreasureCorrectlyAssigned(M1PublicTests.java:1607)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testInstanceVariableChampionCell" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testInstanceVariableWizardInventorySetter" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testConstructorSlytherinWizard" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testMethodInRavenclawWizardTrait" classname="harrypotter.tests.M1PublicTests" time="0.103">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 100 milliseconds
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M1PublicTests.testMethodExistsInClass(M1PublicTests.java:2014)
	at harrypotter.tests.M1PublicTests.testMethodInRavenclawWizardTrait(M1PublicTests.java:1375)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testInstanceVariableTaskAllowedMovesGetter" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testConstructorObstacleCellInitialization" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableWizardLocationGetter" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testFirstTaskMapPotionCount" classname="harrypotter.tests.M1PublicTests" time="0.018"/>
    <testcase name="testEnumDirection" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testInstanceVariableTournamentSpellsSetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableWizardTraitCooldownGetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableTaskPotionsSetter" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testInstanceVariableHpObstacleGetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testMethodLoadPotionsInTask" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testInstanceVariablesThirdTaskInherited" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableTaskAllowedMovesSetter" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testFirstTaskMapPotionRandomlyChosen" classname="harrypotter.tests.M1PublicTests" time="0.223"/>
    <testcase name="testClassIsSubClassChampionCell" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testInstanceVariableTaskPotions" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableWizardLocationSetter" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testInstanceVariableTournamentSpells" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testClassImplementsInterfaceGryffindorWizard" classname="harrypotter.tests.M1PublicTests" time="0.104">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 100 milliseconds
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M1PublicTests.testClassImplementsInterface(M1PublicTests.java:2119)
	at harrypotter.tests.M1PublicTests.testClassImplementsInterfaceGryffindorWizard(M1PublicTests.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testConstructorCollectible" classname="harrypotter.tests.M1PublicTests" time="0.004"/>
    <testcase name="testInstanceVariableWizardTraitCooldownSetter" classname="harrypotter.tests.M1PublicTests" time="0.007"/>
    <testcase name="testSecondConstructorWizard" classname="harrypotter.tests.M1PublicTests" time="0.029">
      <failure>java.lang.AssertionError: Missing constructor with String and int and int  parameters in harrypotter.model.character.Wizard class.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at harrypotter.tests.M1PublicTests.testConstructorExists(M1PublicTests.java:2083)
	at harrypotter.tests.M1PublicTests.testSecondConstructorWizard(M1PublicTests.java:1411)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testInstanceVariableHpObstacleSetter" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testInstanceVariableWizardDefaultHp" classname="harrypotter.tests.M1PublicTests" time="0.005"/>
    <testcase name="testInstanceVariableWizardDefaultIp" classname="harrypotter.tests.M1PublicTests" time="0.005"/>
    <testcase name="testConstructorPhysicalObstacle" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testConstructorChampionCell" classname="harrypotter.tests.M1PublicTests" time="0.004"/>
    <testcase name="testInstanceVariableCollectible" classname="harrypotter.tests.M1PublicTests" time="0.003"/>
    <testcase name="testLoadSpellsMethod" classname="harrypotter.tests.M1PublicTests" time="0.015">
      <failure>java.lang.AssertionError: Failed to create a new instance of the Tournment class.
An Exception was raised: java.lang.NullPointerException
	at org.junit.Assert.fail(Assert.java:88)
	at harrypotter.tests.M1PublicTests.testLoadSpellsMethod(M1PublicTests.java:1288)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testInstanceVariableTaskMapGetter" classname="harrypotter.tests.M1PublicTests" time="0.002"/>
    <testcase name="testClassIsSubClassRelocatingSpell" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testThirdTaskMapPotionRandomlyChosen" classname="harrypotter.tests.M1PublicTests" time="0.008">
      <error>java.lang.NullPointerException
	at harrypotter.model.tournament.Task.task3(Task.java:224)
	at harrypotter.model.tournament.ThirdTask.generateMap(ThirdTask.java:29)
	at harrypotter.model.tournament.Task.&lt;init&gt;(Task.java:57)
	at harrypotter.model.tournament.ThirdTask.&lt;init&gt;(ThirdTask.java:12)
	at harrypotter.tests.M1PublicTests.testThirdTaskMapPotionRandomlyChosen(M1PublicTests.java:1794)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testFirstTaskMapChampionLocation" classname="harrypotter.tests.M1PublicTests" time="0.109">
      <failure>java.lang.AssertionError: The first champion position is incorrect.
Note: the coordinates of the first champion should match the bottom left cell of the 2D-array regardless of his/her coordinates in the map.
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at harrypotter.tests.M1PublicTests.testFirstTaskMapChampionLocation(M1PublicTests.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</failure>
    </testcase>
    <testcase name="testInstanceVariableHufflepuffWizardInherited" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testConstructorTournament" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableSlytherinWizardTraitDiretion" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableSlytherinWizardTraitDiretionGetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariablesGryffindorWizardInherited" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testSecondTaskMapMerpersonDmgHpRandom" classname="harrypotter.tests.M1PublicTests" time="5.004">
      <error>org.junit.runners.model.TestTimedOutException: test timed out after 5000 milliseconds
	at harrypotter.model.tournament.Task.task2(Task.java:171)
	at harrypotter.model.tournament.SecondTask.generateMap(SecondTask.java:21)
	at harrypotter.model.tournament.Task.&lt;init&gt;(Task.java:57)
	at harrypotter.model.tournament.SecondTask.&lt;init&gt;(SecondTask.java:11)
	at harrypotter.tests.M1PublicTests.testSecondTaskMapMerpersonDmgHpRandom(M1PublicTests.java:1429)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testClassIsSubClassEmptyCell" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testThirdTaskReadMap" classname="harrypotter.tests.M1PublicTests" time="0.003">
      <error>java.lang.NullPointerException
	at harrypotter.model.tournament.Task.task3(Task.java:224)
	at harrypotter.model.tournament.ThirdTask.generateMap(ThirdTask.java:29)
	at harrypotter.model.tournament.Task.&lt;init&gt;(Task.java:57)
	at harrypotter.model.tournament.ThirdTask.&lt;init&gt;(ThirdTask.java:12)
	at harrypotter.tests.M1PublicTests.testThirdTaskReadMap(M1PublicTests.java:1864)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
    <testcase name="testInstanceVariableTaskMapSetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableWizardSpellsGetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testInstanceVariableTaskChampionsGetter" classname="harrypotter.tests.M1PublicTests" time="0.001"/>
    <testcase name="testClassIsSubClassCollectibleCell" classname="harrypotter.tests.M1PublicTests" time="0.006"/>
    <testcase name="testInstanceVariableSpellCoolDownGetter" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testInstanceVariableHpObstacle" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testInstanceVariableCollectibleGetter" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testInstanceVariableTaskTraitPotionsGetter" classname="harrypotter.tests.M1PublicTests" time="0.0"/>
    <testcase name="testThirdTaskMapPotionCount" classname="harrypotter.tests.M1PublicTests" time="0.004">
      <error>java.lang.NullPointerException
	at harrypotter.model.tournament.Task.task3(Task.java:224)
	at harrypotter.model.tournament.ThirdTask.generateMap(ThirdTask.java:29)
	at harrypotter.model.tournament.Task.&lt;init&gt;(Task.java:57)
	at harrypotter.model.tournament.ThirdTask.&lt;init&gt;(ThirdTask.java:12)
	at harrypotter.tests.M1PublicTests.testThirdTaskMapPotionCount(M1PublicTests.java:1755)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:52)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

</error>
    </testcase>
  </testsuite>
</testrun>
